### ISSUE TITLE
Implement battery temperature and health

### ISSUE THREAD

**Issue by direc85** [direc85/harbour-batterybuddy#42]
- [x] Read battery temperature and health from file
- [x] Display the data in GUI application
- [x] Add relevant settings to control daemon behavior
- [x] Implement notifications daemon

Verify functionality on different devices:

- [x] Jolla Phone
- [x] Xperia X
- [x] Xperia XA2
- [x] Xperia X10

**Comment by direc85** [comment]
Work started in #40

**Comment by direc85** [comment]
@nephros tested the file with Xperia X10, I tested it with Xperia XA2 (Ultra) - ticked two boxes more.

**Comment by nephros** [comment]
> @nephros tested the file with Xperia X10, I tested it with Xperia XA2 (Ultra) - ticked two boxes more.

Nice! I develop on Xperia 10, so that should usually work. I can also test on Gemini, but as that doesn't have the charge control feature AFAIK that's of little use.

**Comment by nephros** [comment]
possibility to check box number 3 in #43

**Comment by nephros** [comment]
Just leaving a note here so I don't forget:

On Xperia10 there is /sys/class/power_supply/bms  (Battery Management/Monitoring System??), which has these:

    temp_cold
    temp_cool
    temp_hot
    temp_warm

Which seem to set the thresholds for the "health" reporting. Could be used (they are writable), but I'm not sure it's smart to expose them to users.

**Comment by direc85** [comment]
It really is not a good idea to let users set the tresholds, but nice to know those exist :)

**Comment by direc85** [comment]
The health and temperature files fortunately are in the same location across my devices (Jolla, X, XA2) and X10, too! Release gets closer and closer :)

The bad news is that `Notification.setSound` doesn't exist in SFOS 3.4 and earlier, so I'll have to create a separate branch for the older releases. I'm considering SFOS 3.0, because I just can't get the app sdk installing SFOS 2.2 build engine any more...

**Comment by direc85** [comment]
Well, I ended up using defines and conditional compiling to reach that goal. I decided to use the legacy code path for SFOS 4 releases, too, since it still works fine (although I still feel it's a bit of a hack...)

Released in commit 1dd00da
